// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05kna8xTKBcTGfs8kvvrpVC7D7kRelek',
    appId: '1:95940756965:web:3865ecbc6d0fd6f76d9b0c',
    messagingSenderId: '95940756965',
    projectId: 'crudfirebase-7e2c3',
    authDomain: 'crudfirebase-7e2c3.firebaseapp.com',
    storageBucket: 'crudfirebase-7e2c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFiAZ8mb-AXMg8CM2nm4IF9QZpCvpqY18',
    appId: '1:95940756965:android:f3240ffef40fc71e6d9b0c',
    messagingSenderId: '95940756965',
    projectId: 'crudfirebase-7e2c3',
    storageBucket: 'crudfirebase-7e2c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyC1NTdvYOL7_vnVaRky_ldgDlpHwGCM',
    appId: '1:95940756965:ios:8a49c14fb47c6c916d9b0c',
    messagingSenderId: '95940756965',
    projectId: 'crudfirebase-7e2c3',
    storageBucket: 'crudfirebase-7e2c3.appspot.com',
    iosClientId: '95940756965-lfkj7le60a6p0gq4n1mjhb6f0i1hop1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyC1NTdvYOL7_vnVaRky_ldgDlpHwGCM',
    appId: '1:95940756965:ios:8a49c14fb47c6c916d9b0c',
    messagingSenderId: '95940756965',
    projectId: 'crudfirebase-7e2c3',
    storageBucket: 'crudfirebase-7e2c3.appspot.com',
    iosClientId: '95940756965-lfkj7le60a6p0gq4n1mjhb6f0i1hop1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebase',
  );
}
